baseURL = 'https://MelvinRongHuiHoo.github.io/'
languageCode = 'nl-nl'
title = 'Mijn Portfolio'
theme = "paper"

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
 # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
 # github = 'YOUR_GITHUB_ID'                 # github.com/YOUR_GITHUB_ID
 # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
 # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
 # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/157750319'                 # gravatar email or image url
  name = 'YOUR_NAME'
  bio = 'YOUR_BIO'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
